import os
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from models.campaign import CampaignBrief

def add_slide(prs, layout_index=6):
    layout = prs.slide_layouts[layout_index]
    return prs.slides.add_slide(layout)

def set_background(slide, r, g, b):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(r, g, b)

def add_textbox(slide, text, left, top, width, height,
                font_size=18, bold=False, color=(0, 0, 0),
                align=PP_ALIGN.LEFT, wrap=True):
    txBox = slide.shapes.add_textbox(
        Inches(left), Inches(top), Inches(width), Inches(height)
    )
    txBox.word_wrap = wrap
    tf = txBox.text_frame
    tf.word_wrap = wrap
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.color.rgb = RGBColor(*color)
    return txBox

def generate_deck(brief: CampaignBrief, output_path: str = "output/campaign_deck.pptx"):
    os.makedirs("output", exist_ok=True)
    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    WHITE = (255, 255, 255)
    BLACK = (30, 30, 30)
    ACCENT = (99, 102, 241)
    LIGHT_GRAY = (245, 245, 247)
    PLACEHOLDER_GRAY = (220, 220, 225)

    # --- Slide 1: Campaign Name ---
    slide1 = add_slide(prs)
    set_background(slide1, *ACCENT)
    add_textbox(slide1, brief.campaign_name,
                1, 2.5, 11, 2,
                font_size=40, bold=True, color=WHITE,
                align=PP_ALIGN.CENTER)
    add_textbox(slide1, "Campaign Brief — Auto-generated by Campaign Agent",
                1, 4.2, 11, 0.8,
                font_size=14, color=WHITE,
                align=PP_ALIGN.CENTER)

    # --- Slide 2: Overview ---
    slide2 = add_slide(prs)
    set_background(slide2, *LIGHT_GRAY)
    add_textbox(slide2, "Campaign Overview",
                0.5, 0.3, 12, 0.8,
                font_size=28, bold=True, color=ACCENT)

    details = f"Objective:    {brief.objective}\n\nLaunch Date:  {brief.launch_date or 'TBD'}\n\nDRI:          {brief.dri or 'TBD'}"
    add_textbox(slide2, details,
                0.5, 1.3, 8, 3,
                font_size=16, color=BLACK)

    if brief.segments:
        seg = brief.segments[0]
        seg_text = f"Primary Segment\n{seg.name}\n\n{seg.criteria}\n\nEst. Size: {seg.size or 'TBD'}"
        box = slide2.shapes.add_textbox(Inches(9), Inches(1.3), Inches(3.8), Inches(3.5))
        box.word_wrap = True
        fill = box.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(*ACCENT)
        tf = box.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        run = p.add_run()
        run.text = seg_text
        run.font.size = Pt(13)
        run.font.color.rgb = RGBColor(*WHITE)

    if brief.compliance_flags:
        flags = "⚠️ Compliance Flags\n" + "\n".join(f"• {f}" for f in brief.compliance_flags)
        add_textbox(slide2, flags,
                    0.5, 5.5, 12, 1.5,
                    font_size=13, color=(180, 60, 60))

    # --- Deliverable Slides ---
    for deliverable in brief.deliverables:
        slide = add_slide(prs)
        set_background(slide, *WHITE)

        # header bar
        header = slide.shapes.add_textbox(Inches(0), Inches(0), Inches(13.33), Inches(0.8))
        header.fill.solid()
        header.fill.fore_color.rgb = RGBColor(*ACCENT)
        tf = header.text_frame
        p = tf.paragraphs[0]
        run = p.add_run()
        run.text = deliverable.name
        run.font.size = Pt(20)
        run.font.bold = True
        run.font.color.rgb = RGBColor(*WHITE)
        p.alignment = PP_ALIGN.LEFT

        # left side — copy
        copy_lines = []
        if deliverable.subject_line:
            copy_lines.append(f"Subject Line:\n{deliverable.subject_line}")
        if deliverable.preview_text:
            copy_lines.append(f"Preview Text:\n{deliverable.preview_text}")
        if deliverable.body:
            copy_lines.append(f"Body:\n{deliverable.body}")
        if deliverable.cta:
            copy_lines.append(f"CTA:\n{deliverable.cta}")

        copy_text = "\n\n".join(copy_lines) if copy_lines else "No copy extracted."
        add_textbox(slide, copy_text,
                    0.3, 1.0, 6.2, 6.0,
                    font_size=12, color=BLACK)

        # right side — placeholder image box
        ph = slide.shapes.add_textbox(
            Inches(6.8), Inches(1.0), Inches(6.0), Inches(5.8)
        )
        ph.word_wrap = True
        fill = ph.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(*PLACEHOLDER_GRAY)
        tf = ph.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        run = p.add_run()
        run.text = f"[ {deliverable.channel.upper()} DESIGN ]\n\nFigma asset goes here\n\nNode ID: TBD"
        run.font.size = Pt(14)
        run.font.color.rgb = RGBColor(150, 150, 160)

    prs.save(output_path)
    print(f"✅ Deck saved to {output_path}")
    return output_path